### ISSUE TITLE
Input Path Configuration

### ISSUE THREAD

**Issue by bellini-ea** [simonharrer/gradle-graphviz-plugin#1]
Be great if the input path (location of the .dot source file) could be configurable since my .dot file is generated and so it ends up in the /build dir.  For example, I'm using this project: https://github.com/mmalohlava/gradle-visteg to generate a graph of the gradle tasks.  Your project here would be a nice compliment to that.  Some to consider if it works for you.

**Comment by simonharrer** [comment]
Thanks for your issue. But I want to keep the plugin clean. But feel free to fork it and build upon it (it's MIT licensed, so you can do whatever you want with it).
